version: '3'

services:

  moroback:    
    image: "docker.io/boyangyang/moroback:latest"
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: unless-stopped
   

